@RasyonetInternshipApi_HostAddress = http://localhost:5119

GET {{RasyonetInternshipApi_HostAddress}}/api/stocks
Accept: application/json

###

POST {{RasyonetInternshipApi_HostAddress}}/api/stocks
Content-Type: application/json

{
  "symbol": "AAPL",
  "companyName": "Apple Inc."
}

###

POST {{RasyonetInternshipApi_HostAddress}}/api/stocks/AAPL/refresh
Accept: application/json

###

GET {{RasyonetInternshipApi_HostAddress}}/api/analytics/top-gainers?count=5
Accept: application/json

###
